CfgFile: CfgFileException.o CfgFile.o
	g++ -o CfgFile CfgFileException.o CfgFile.o

CfgFileException.o: CfgFileException/CfgFileException.h CfgFileException/CfgFileException.cpp
	g++ -c CfgFileException/CfgFileException.cpp
	
CfgFile.o: CfgFile.h CfgFile.cpp
	g++ -c CfgFile.cpp
	
